version: '3.9'

services:
  db:
    image: postgres:17
    container_name: student_db
    restart: always
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2557740
    ports:
      - "5432:5432"
    volumes:
      - student_db_data:/var/lib/postgresql/data

volumes:
  student_db_data: