spring.application.name=student_management_system



spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=2557740
spring.jpa.hibernate.ddl-auto=update